networks:
  default:
    driver: bridge
    name: roboshop
    external: true 

services:
  mongodb:
    image: avkvamsi/mongodb:v1
    container_name: mongodb
  catalogue:
    image: avkvamsi/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
  user:
    image: avkvamsi/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: avkvamsi/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: avkvamsi/mysql:v1
    container_name: mysql
  shipping:
    image: avkvamsi/shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  