networks:
  default:
    driver: bridge
    name: roboshop
    #external: true 
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
    image: avkvamsi/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: avkvamsi/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: avkvamsi/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: avkvamsi/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: avkvamsi/mysql:v1
    container_name: mysql
  shipping:
    image: avkvamsi/shipping:v1
    container_name: shipping
    volumes:
    - mysql:/var/lib/mysql
    depends_on:
    - cart
    - mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  payment:
    image: avkvamsi/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend:
    image: avkvamsi/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment


